---
title: "Verkenning fysicochemische metadata eDNA bodemstalen"
author: "Sam Lambrechts, Bruno De Vos, Hans Van Calster"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    toc: true
    toc_depth: 2
    toc_float: true
    code_folding: "hide"
---

```{r setup, include=FALSE}
library(knitr)
opts_knit$set(root.dir = here::here())
opts_chunk$set(echo = TRUE)
library(car)
library(corrplot)
library(dplyr)
library(moments)
library(magick)
conflicted::conflicts_prefer(dplyr::select, dplyr::filter)

```


# Inlezen data

```{r inlezen}
mbag_shared_drive <- "G:/Gedeelde drives/PRJ_MBAG"

subdirectory <- "4c_bodembiodiversiteit/data/Stratificatie_MBAG_plots"

full_directory_path <- file.path(mbag_shared_drive, subdirectory)

file_name <- "MBAG_stratfile_v2_cleaned_12.csv"

file_path <- file.path(full_directory_path, file_name)

df <- read.csv(file_path, stringsAsFactors = FALSE)

```

Select numeric columns and remove columns with zero variance

```{r}

numeric_cols <- sapply(df, is.numeric)
df_numeric <- df[, numeric_cols]

df_numeric_clean <- df_numeric[, apply(df_numeric, 2, var, na.rm = TRUE) != 0]

```

Pairwise correlations

```{r pairwise-correlations}
cor_matrix <- cor(df_numeric_clean, use = "pairwise.complete.obs")

png("correlation_plot.png", width = 1200, height = 1000)
corrplot(cor_matrix, method = "color", type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45, tl.cex = 0.7)
dev.off()
```


```{r dispay-corrplot}
# Display correlation plot
plot(1:10, type = "n", xlab = "", ylab = "", main = "Correlation Plot")
img <- png::readPNG("correlation_plot.png")
grid::grid.raster(img)
```

Multicollinearity test

```{r multicollinearity}
constant_response <- rep(1, nrow(df_numeric_clean))
vif_model <- lm(constant_response ~ ., data = df_numeric_clean)
vif_results <- vif(vif_model)
```

```{r display-vif-results}
print(vif_results)
```

```{r Display-highly-correlated-pairs}
high_cor <- which(abs(cor_matrix) > 0.7 & abs(cor_matrix) < 1, arr.ind = TRUE)
high_cor_pairs <- data.frame(
  Var1 = rownames(cor_matrix)[high_cor[,1]],
  Var2 = colnames(cor_matrix)[high_cor[,2]],
  Correlation = cor_matrix[high_cor]
)
high_cor_pairs <- high_cor_pairs[!duplicated(t(apply(high_cor_pairs[,1:2], 1, sort))),]
high_cor_pairs <- high_cor_pairs[order(-abs(high_cor_pairs$Correlation)),]
print(high_cor_pairs)
```


```{r summary-stats}
summary_stats <- df_numeric_clean %>%
  summarise(across(everything(), list(
    mean = ~mean(., na.rm = TRUE),
    sd = ~sd(., na.rm = TRUE),
    min = ~min(., na.rm = TRUE),
    max = ~max(., na.rm = TRUE)
  )))
print(summary_stats)

```


Calculate skewness and kurtosis

```{r}
skewness_values <- apply(df_numeric, 2, function(x) ifelse(all(is.na(x)), NA, moments::skewness(x, na.rm = TRUE)))
kurtosis_values <- apply(df_numeric, 2, function(x) ifelse(all(is.na(x)), NA, moments::kurtosis(x, na.rm = TRUE)))

skew_kurt <- data.frame(
  variable = names(df_numeric),
  skewness = skewness_values,
  kurtosis = kurtosis_values
)
```


Print skewness and kurtosis

```{r}
print(skew_kurt)

```


Create histograms and Q-Q plots for each numeric variable

```{r}
for (col in names(df_numeric)) {
  png(paste0(col, "_diagnostic_plots.png"), width = 800, height = 400)
  par(mfrow = c(1, 2))
  
  # Histogram
  hist(df_numeric[[col]], main = paste("Histogram of", col), xlab = col)
  
  # Q-Q plot
  qqnorm(df_numeric[[col]], main = paste("Q-Q Plot of", col))
  qqline(df_numeric[[col]], col = "red")
  
  dev.off()
}

```


Print the generated plot files

```{r}
# List the plot files
plot_files <- list.files(pattern = "*_diagnostic_plots.png")

# Loop through each plot file and display it
for (plot_file in plot_files) {
  img <- image_read(plot_file)  # Read the image file
  print(img)                    # Display the image in the plot window
}
```

